### ISSUE TITLE
APCu not present / need web server restart at the end of a full bootstrap

### ISSUE THREAD

**Issue by PVince81** [owncloud-ansible/owncloud#17]
Already two times it happened to me that when running setup.yml with an empty machine, it would install everything and at the end ownCloud would say that the "APCu is not present".
After manually restarting Apache the module was found.

This might be some kind of race condition as it doesn't happen every time.

To fix it, we should probably add an Apache restart at the end, or at least after the PHP steps.

**Comment by JKawohl** [comment]
can second that, happened to me, too. I guess this happens when you interrupt and restart the installation.

**Comment by xoxys** [comment]
Right, and that's how Ansible (or at lease handlers) work. A handler will be triggered by a "changed" task. You also have to know, that by default all triggered handlers will run at last after a successful play.

So if your play gets interrupted (by any reason) before the triggered handlers finished running, the will not triggered again on the next play because the dependent task is already changed.

> To fix it, we should probably add an Apache restart at the end, or at least after the PHP steps.

Bad practice, because 
- it will break Ansibles idempotency rule
- it will restart (and that means a short interruption of your running ownCloud) on every Playbook run even if nothing changed and a restart is not necessary

**Comment by enbrnz** [comment]
So can we close this issue as won't fix, or is there a possible solution to this problem?

**Comment by xoxys** [comment]
Close it
